name: OIDC smoke test

on:
    workflow_dispatch:
permissions:
    id-token: write
    contents: read
jobs:
    whoami:
        name: Verify OIDC login to azure
        runs-on: ubuntu-latest
        steps:
            - name: Azure Login(OIDC)
              uses: azure/login@v2
              with:
                  client-id: ${{vars.AZURE_CLIENT_ID}}
                  tenant-id: ${{vars.AZURE_TENANT_ID}}
                  subscription-id: ${{vars.AZURE_SUBSCRIPTION_ID}}
            - name: show identity
              run: az account show --output table
